### TEST GET / WEBSITE

GET http://localhost:8383/


### TEST GET ENDPOINT

GET http://localhost:8383/api/data

### TEST POST ENDPOINT

POST http://localhost:8383/api/data
Content-Type: application/json

{
  "name":"Doe"
}